In [17]:
import numpy as np

def bernoulli_kld(p, q):
    kld = np.sum(p * np.log(p/q) + (1 - p) * np.log((1 - p)/(1 - q)))
    return kld

def bernoulli_reparam_kld(p, q_mean, q_logvar):
    eps = np.random.normal(size=q_mean.shape)
    q = sigmoid(q_mean + np.exp(0.5 * q_logvar) * eps)
    kld = bernoulli_kld(p, q) - 0.5 * np.sum(1 + q_logvar - q_mean**2 - np.exp(q_logvar))
    return kld

def sigmoid(x):
    return 1 / (1 + np.exp(-x))



In [3]:
q_logvar

array([-4.60517019, -3.21887582])

In [ ]:
# Example usage
p = np.array([0.2, 0.8])
q_mean = np.array([0.3, 0.7])
q_logvar = np.log(np.array([0.1, 0.2])**2)
kld = bernoulli_reparam_kld(p, q_mean, q_logvar)
print(kld)

#### https://davidstutz.de/bernoulli-variational-auto-encoder-in-torch/

In [24]:
import tensorflow as tf 

In [23]:
pred_y= 0.5
y = 0.5 # 가설 분포값 fixed

tf.math.log(pred_y) - tf.math.log(y) + tf.math.log(1-pred_y) - tf.math.log(1-y) 


<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
zi=g(y,ϵ)=σ(lnϵ−ln(1−ϵ)+lnθi(y)−ln(1−θi(y)))

In [5]:
import tensorflow as tf

def compute_z(theta, y, eps):
    log_eps = tf.math.log(eps)
    log_one_minus_eps = tf.math.log(1 - eps)
    log_theta = tf.math.log(theta(y))
    log_one_minus_theta = tf.math.log(1 - theta(y))
    logit = log_eps - log_one_minus_eps + log_theta - log_one_minus_theta
    return tf.math.sigmoid(logit)

# Example usage
theta = tf.keras.Sequential([tf.keras.layers.Dense(10), tf.keras.layers.Dense(1, activation='sigmoid')])
y = tf.ones((1, 10)) * 0.001
eps = tf.random.uniform((1, 10))
z = compute_z(theta, y, eps)
print(z)

tf.Tensor(
[[0.87516546 0.5491649  0.17724568 0.952958   0.54801315 0.26864618
  0.6722696  0.7926336  0.47837663 0.80601096]], shape=(1, 10), dtype=float32)


In [1]:
import tensorflow_probability as tfp
x = tfp.distributions.Bernoulli(probs=0.7).sample(sample_shape=(10, 10))

In [15]:
tfp.distributions.Bernoulli(probs=0.7).sample(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 1, 1, 1, 0, 1, 1, 1, 1])>