In [5]:
import numpy as np

In [7]:
np.random.seed(42)
N = 1000
L = np.random.normal(size=N)

# Step 2: Set parameters
m = 2
r = 0.2 * np.std(y)  # tolerance

In [11]:
N = len(L)
B = 0.0
A = 0.0

# Split time series and save all templates of length m
xmi = np.array([L[i : i + m] for i in range(N - m)])
xmj = np.array([L[i : i + m] for i in range(N - m + 1)])

# Save all matches minus the self-match, compute B
B = np.sum([np.sum(np.abs(xmii - xmj).max(axis=1) <= r) - 1 for xmii in xmi])

# Similar for computing A
m += 1
xm = np.array([L[i : i + m] for i in range(N - m + 1)])

A = np.sum([np.sum(np.abs(xmi - xm).max(axis=1) <= r) - 1 for xmi in xm])

-np.log(A / B)

2.0864394708674805

In [29]:
L[-10:]

array([ 0.20838281, -2.04173487, -0.24717738, -0.68198425, -1.00162001,
       -0.28110029,  1.79768653,  0.64084286, -0.57117899,  0.57258278])

In [28]:
xmi[-1]

array([ 1.79768653,  0.64084286, -0.57117899])

In [27]:
xmj[-1]

array([ 0.64084286, -0.57117899,  0.57258278])

In [31]:
import numpy as np

# 시계열 데이터셋 생성 (0 ~ 1 사이의 무작위 100개의 숫자)
data = np.random.rand(100)

# 샘플 엔트로피를 계산하기 위한 초기값 설정
m = 2
r = 0.2
N = len(data)

# 데이터를 m-길이의 벡터로 변환
vectors = [data[i:i+m] for i in range(N-m+1)]

# 각 벡터 간의 거리 계산 및 거리가 r 이내인 벡터의 개수 세기
A = np.zeros(len(vectors))
B = np.zeros(len(vectors))

for i in range(len(vectors)):
    for j in range(i, len(vectors)):
        dist = np.abs(vectors[i] - vectors[j]).max()
        if dist < r:
            B[i] += 1
            if j < len(vectors) - 1:
                A[i] += 1

# A와 B에서 0을 제외
A = A[A!=0]
B = B[B!=0]

# 샘플 엔트로피 계산
sample_entropy = np.log(A/B).mean()

print(f'Sample Entropy: {sample_entropy}')

ValueError: operands could not be broadcast together with shapes (98,) (99,) 