The Discrete Fourier Transform (DFT) of a sequence is defined by the formula:

$$ X[k] = \sum_{n=0}^{N-1} x[n] \cdot e^{-j\frac{2\pi}{N}kn} $$

where:
- $N$ is the number of samples,
- $x[n]$ is the $n$-th sample in the time domain,
- $X[k]$ is the result of the DFT, representing the frequency domain,
- $k$ is the index in the frequency domain ranging from 0 to $N-1$,
- $j$ is the imaginary unit.

The code performs the following steps:
1. Determine the number of samples $N$ from the size of the input array `x`.
2. Create an array `n` which is a sequence of integers from 0 to $N-1$ that represent the sample indices.
3. Reshape `n` into a column vector `k` to facilitate matrix multiplication.
4. Construct the DFT matrix `M` using the exponential function, which encapsulates the complex sinusoids for the DFT.
5. Compute the DFT by multiplying the matrix `M` with the input array `x`.

The output is an array of complex numbers where each element corresponds to a specific frequency component:
- The first element is the DC component, which represents the average value of the signal.
- The following elements represent the signal's content at increasing frequencies, with the magnitude indicating the amplitude and the angle indicating the phase shift of each frequency component.


In [22]:
import numpy as np

def DFT_multi_samples(x):
    """
    Compute the Discrete Fourier Transform (DFT) for multiple samples.
    
    :param x: 2D array where each row is a sample sequence
    :return: 2D array where each row is the DFT of the corresponding sequence
    """
    N = x.shape[1]  # Number of samples per sequence (assuming each sequence is along the second axis)
    n = np.arange(N)
    k = n.reshape((N, 1))
    M = np.exp(-2j * np.pi * k * n / N)
    return np.dot(x, M.T)  # Matrix multiplication with the transpose of M

# Example usage with multiple samples:
x_multi = np.array([[0, 1, 2], [5, 5, 2]])  # Two sample sequences
dft_multi = DFT_multi_samples(x_multi)
dft_multi

array([[ 3. +0.j        , -1.5+0.8660254j , -1.5-0.8660254j ],
       [12. +0.j        ,  1.5-2.59807621j,  1.5+2.59807621j]])

# Discrete Fourier Transform (DFT) Calculation for Multiple Samples

When we have multiple time-domain sample sequences, we can apply the Discrete Fourier Transform (DFT) to each sequence to convert them into their frequency-domain representations. The process for calculating the DFT for multiple samples is outlined below, with numerical substitutions to illustrate the steps:

## Step 1: Define the DFT Equation

The DFT for a single sample sequence is given by the equation:

$$ X[k] = \sum_{n=0}^{N-1} x[n] \cdot e^{-j\frac{2\pi}{N}kn} $$

## Step 2: Extend to Multiple Samples

For multiple samples, the DFT is calculated for each sequence individually. Consider two sample sequences:

$$ x_{multi} = \begin{bmatrix}
0 & 1 & 2 & 3 \\
4 & 5 & 6 & 7 \\
\end{bmatrix} $$

## Step 3: Calculate the DFT Matrix

Construct the DFT matrix $M$ for $N=4$ (since we have 4 points in each sequence):

$$ M = \begin{bmatrix}
e^{-j\frac{2\pi}{4}0\cdot0} & e^{-j\frac{2\pi}{4}0\cdot1} & e^{-j\frac{2\pi}{4}0\cdot2} & e^{-j\frac{2\pi}{4}0\cdot3} \\
e^{-j\frac{2\pi}{4}1\cdot0} & e^{-j\frac{2\pi}{4}1\cdot1} & e^{-j\frac{2\pi}{4}1\cdot2} & e^{-j\frac{2\pi}{4}1\cdot3} \\
e^{-j\frac{2\pi}{4}2\cdot0} & e^{-j\frac{2\pi}{4}2\cdot1} & e^{-j\frac{2\pi}{4}2\cdot2} & e^{-j\frac{2\pi}{4}2\cdot3} \\
e^{-j\frac{2\pi}{4}3\cdot0} & e^{-j\frac{2\pi}{4}3\cdot1} & e^{-j\frac{2\pi}{4}3\cdot2} & e^{-j\frac{2\pi}{4}3\cdot3} \\
\end{bmatrix} $$

## Step 4: Perform Matrix Multiplication

For each sample sequence $x[m]$, compute the DFT by multiplying with the transpose of the DFT matrix:

$$ X_{multi}[m] = x_{multi}[m] \cdot M^T $$

## Step 5: Numerical Example

Let's calculate the DFT for the first sequence $[0, 1, 2, 3]$:

$$ X[0] = (0 \cdot 1 + 1 \cdot 1 + 2 \cdot 1 + 3 \cdot 1) = 6 $$
$$ X[1] = (0 \cdot 1 + 1 \cdot (-j) + 2 \cdot (-1) + 3 \cdot j) = -2 + 2j $$
$$ X[2] = (0 \cdot 1 + 1 \cdot (-1) + 2 \cdot 1 + 3 \cdot (-1)) = -2 $$
$$ X[3] = (0 \cdot 1 + 1 \cdot j + 2 \cdot (-1) + 3 \cdot (-j)) = -2 - 2j $$

Perform the same calculation for the second sequence $[4, 5, 6, 7]$.

## Conclusion

By substituting the values of $n$, $k$, and $x[n]$ into the DFT equation and computing the sum, we can find the frequency-domain representation for each time-domain sample sequence.


# Fast Fourier Transform (FFT)

The Fast Fourier Transform (FFT) is an algorithm that computes the Discrete Fourier Transform (DFT) of a sequence, or its inverse, efficiently.

## DFT Definition

The DFT is defined as:

$$ X[k] = \sum_{n=0}^{N-1} x[n] \cdot e^{-j\frac{2\pi}{N}kn} $$

where:
- \( N \) is the sample size,
- \( x[n] \) is the input sequence,
- \( X[k] \) is the output sequence,
- \( k \) ranges from 0 to \( N-1 \).

## Cooley-Tukey FFT Algorithm

The Cooley-Tukey FFT algorithm exploits the periodicity and symmetry properties of the DFT.

### Radix-2 Decimation-In-Time (DIT) FFT

For a sequence of size \( N \), which is a power of 2 (i.e., \( N = 2^m \)), the DFT can be divided into two smaller DFTs:

1. DFT of the even-indexed part of the sequence.
2. DFT of the odd-indexed part of the sequence.

This process is recursively applied to break the DFT into smaller DFTs until the size becomes 1.

## FFT Python Implementation (without using `np.fft`)

Here's a Python function implementing a simple recursive FFT algorithm:




In [20]:
import numpy as np

def FFT(x):
    N = len(x)
    if N <= 1:
        return x
    even = FFT(x[0::2])
    odd = FFT(x[1::2])
    T = [np.exp(-2j * np.pi * k / N) * odd[k] for k in range(N // 2)]
    return [even[k] + T[k] for k in range(N // 2)] + [even[k] - T[k] for k in range(N // 2)]

# Example usage:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7])  # Example input sequence
fft_result = FFT(x)

In [26]:
fft_result[0]

(28+0j)

In [29]:
import tensorflow as tf

# Make sure you have a complex data type
complex_tensor = tf.constant([1+2j, 3+4j, 5+6j])

# Extract the imaginary parts
imaginary_parts_tf = tf.math.imag(complex_tensor)

print(imaginary_parts_tf)  # Output: [2. 4. 6.]


tf.Tensor([2. 4. 6.], shape=(3,), dtype=float64)


In [31]:
tf.math.angle(complex_tensor)*180/np.pi

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([63.43494882, 53.13010235, 50.19442891])>